spring.application.name=acme-salary-management
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/salary_management}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

app.seed.enabled=true
app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:4200}
